#!/bin/bash
source=${3}
branch=${4}
server=${1}
org=${2}
file_source=$(echo ${source} | tr / _)
rm ${file_source}-${branch}.sh || echo
# https://github.corp.clover.com/clover/tfe-tools/blob/main/modtest
# https://github.corp.clover.com/clover/tfe-tools/blob/main/mod_versions
for x in $(./mod_versions --source=${source} | jq -n "inputs[].Key")
do
	# echo modtest --key=${x} --branch=${branch} >> ${file_source}-${branch}.sh
	echo modtest --org=${org} --server=${server} --key=${x} --branch=${branch} >> ${file_source}-${branch}.sh
done
bash ${file_source}-${branch}.sh
